name: waybox
description: "Minimal configurable launcher menu for Wayland and Waybar workflows."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  wayland_layer_shell:
    git:
      url: https://github.com/ifgar/wayland_layer_shell.git
      ref: master
  window_manager: ^0.5.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/waybox.xml
    - assets/theme.conf
